### ISSUE TITLE
Example won't work

### ISSUE THREAD

**Issue by SebaCoelli** [balor/connect-memcached#19]
I tried to use some of the [Example](https://github.com/balor/connect-memcached#example) code in my app by making a few changes and it didn't worked. After hours of changing my code and 'adapting' it so that the memcached could work I tried to run just the example to know if I was the one wrong here.

So I copy paste the code, and run it and the same problem I was having with my app  happened. When you access the designated URL for your app(example: 127.0.0.1:9341) it will keep loading and loading.

Please if I'm doing something wrong please tell me, otherwise it would be nice if you could fix this problem.

Thank You.

**Comment by Pau1fitz** [comment]
I am experiencing the same issue
