### ISSUE TITLE
Does your library support SASL?

### ISSUE THREAD

**Issue by dorlandode** [balor/connect-memcached#25]
I am looking for an express session store using memcached, but supporting SASL.  Does your library do this?

**Comment by balor** [comment]
Hello there.
My library uses the "memcached" node package (https://github.com/3rd-Eden/memcached) which unfortunately is talking with the memcached server only through ASCII protocol, which excludes the usage of SASL.
Regards

**Comment by rmccullagh** [comment]
Does any client actually support the binary protocol? I've never seen it.

**Comment by dorlandode** [comment]
Yes, after I messaged you I created a project that does what I need.
