### ISSUE TITLE
Confirm memcached connection

### ISSUE THREAD

**Issue by colinbes** [balor/connect-memcached#29]
If using connect-memcached as session store in nodejs how can one confirm connectivity to memcached has occured? 

I am wanting to ensure memcached is up and running and throw error/exception if nodejs application can't connect to memcached.

Thanks

**Comment by beakable** [comment]
I second this :)

**Comment by rmccullagh** [comment]
It would be easy to do it:

```javascript
connectMemcached.client.on('failure', function( details ) { 
    console.log.( "Error " + details.server + "went down due to: " + details.messages.join( '' ) )
 });

```
Look at the Memcached events here: https://github.com/3rd-Eden/memcached#events-1

**Comment by balor** [comment]
rmccullagh solution is pretty valid. Also store could propagate clients event to make the whole task even simpler. 
For sure proper example would be useful in the readme...

**Comment by cainvommars** [comment]
But connect-memcached does not pass these events on. Does it? I tried to capture them and didn't  get any. :/

**Comment by balor** [comment]
@ptrwllrt `connectMemcached.client` is a instance of `Memcached` client, why should connect-memcached propagate anything if you can operate on it directly? You can also create your own `Memcached` client, set handlers and pass it as an option to `MemcachedStore`.

**Comment by balor** [comment]
Closing this issue as it seem out of date. If not, please do reopen it.
