### ISSUE TITLE
user logout automatically

### ISSUE THREAD

**Issue by rajeshpanwar** [balor/connect-memcached#30]
Hi,

I am using connect-memcached("0.2.0;') and  express("3.1.0"). In my web application, there are two interface  admin panel and site interface. I am using different session in both cases. 

In admin panel, i always send backend = 1 in header.

```
var app = module.exports = express();

var session = express.session;
var MemcachedStore = require('connect-memcached')(session);
var host = process.env.MEMCACHE_PORT_11211_TCP_ADDR || sessionServer.host || 'localhost';
var port = process.env.MEMCACHE_PORT_11211_TCP_PORT || sessionServer.port || '11211';

var admin_session = session({
    key: 'admin_token',
    secret: 'aersda@#$32sfas2342',
    cookie: {
        maxAge: 30 * 24 * 60 * 60 * 1000,
    },
    store: new MemcachedStore({
        hosts: host + ":" + port
    })
});
var user_session = session({
    key: 'jsessionid',
    secret: 'aersda@#$32sfas2342',
    cookie: {
        maxAge: 30 * 24 * 60 * 60 * 1000,
    },
    store: new MemcachedStore({
        hosts: host + ":" + port
    })
});
app.use(function (req, res, next) {
    console.log("Setting session ");
    if (req.headers.backend == '1') {
        admin_session(req, res, next);
    } else {
        user_session(req, res, next);
    }
});

```
I am using google cloud instance for memcache.

When user login on my computer, it is working fine but on my client networks, user logout automatically after 10-15 min. 

I console the cookies on server, cookies value is changed automatically and user logout. I don't know why it is happening.

How to debug and resolve it.

If I used redis server for session storage, then everything is working fine.

**Comment by balor** [comment]
Can't really tell from the snippet you provided, maybe some short memcached ttl settings? Did you tried using non-gcp memcached service?
