### ISSUE TITLE
No authentication?

### ISSUE THREAD

**Issue by kboom** [balor/connect-memcached#31]
Trying to get my app working with redis/memcachedcloud but I cannot find any place in config I could put my login and password details in. Does it mean connect-memcached won't work because it does not support authentication?

[memjs](https://github.com/alevy/memjs) has it

and there seems to be a library [connect-memjs](https://github.com/liamdon/connect-memjs) specially for this purpose.

Shouldn't that security be enabled somehow?

**Comment by balor** [comment]
Well, I'm pretty much limited to the underlying client, and as you can read [here](https://github.com/3rd-Eden/memcached/issues/15) this is not an option now. 

I could of course switch the client to memjs, but that piece of code is already there (you've mentioned the connect-memjs).

**Comment by balor** [comment]
Closing this issue for now, as it's more of a different, bigger question - if I should replace current memcached client with `memjs` or leave it be as there is an alternative using it.
