### ISSUE TITLE
Passing in a existing memcached client ignores the secret option

### ISSUE THREAD

**Issue by danielb7390** [balor/connect-memcached#39]
I have a project that already has a memcached instance created, yet when adding `connect-memcached`, it will create a new instance of the client but i wanted to use the existing instance

Took a look at the code and i see i can pass in a `client` at `MemcachedStore()`, but for some reason in case a client is passed the secret option is ignored:

https://github.com/balor/connect-memcached/blob/5116ea30a6d15e7373de7d47cadc9fb5dd56cdf9/lib/connect-memcached.js#L32-L53

Shouldn't the `if (options.secret)` block be outside the `if (!options.client)`?

**Comment by balor** [comment]
@danielb7390 Valid observation, the same applies to `algorithm` option. Luckily I'm planning to do some long due chores on this repository this week so I'll be able to include fix for mentioned quirk.

**Comment by balor** [comment]
Version v2.0.0 should address this issue. In case you're using data encryption, remember to flush the session data before upgrading.
