### ISSUE TITLE
Latest test suite

### ISSUE THREAD

**Issue by jas-** [balor/connect-memcached#42]
Good morning,

While trying to run the new test suite I am receiving `500` responses on the any iteration after the initial request.

```js
$ npm install
$ npm test

> connect-memcached@1.0.0 tests /connect-memcached
> NODE_ENV=test jest --testTimeout=10000

FAIL test/test.js
  Plain memcached session store
    GET / should increment views value at each request (92 ms)
    
  Plain memcached session store > GET / should increment views at each request

  expect(received).toEqual(expected) // deep equality

  Expected: 200
  Received: 500

      10 |     for (var i = 1; i < 50; i++) {
      11 |       const res = await serverAgent.get("/");
   > 12 |       expected(res.status).toEqual(200);
                                                    ^
```

**Comment by balor** [comment]
Thanks, I'll look into it. What node/npm versions you're using?

**Comment by balor** [comment]
Plese note that currently the "correct" test output would be `1 failed, 2 passed, 3 total`, as the last test checks code for the [unfixed issue](https://github.com/balor/connect-memcached/issues/39) related to pre-existing memcached client.

I've did the same steps using `node 17.5.0` on fresh clone and get the "correct" output.

**Comment by jas-** [comment]
Thanks. Looks like my old PR required some additional work as it was double serializing the plaintext prior to encryption. I now have this PR working for both the plain text session and cryptographic session support. I am however running into an issue with the pre-existing connection tests. It seems that if I try to do this manually it is not inserting properly.

**Comment by balor** [comment]
Thanks, I'll look into it. As for this issue I understand that you've managed yourself and this was something local-specific?
