### ISSUE TITLE
Crypto algorithm

### ISSUE THREAD

**Issue by jas-** [balor/connect-memcached#44]
Good morning, I see you have merged the latest crypto functionality updates. An apology is warranted, it seems the algorithm for the latest updates in the `Readme.md` file also needs to change. The default is now `aes-256-gcm`. The remaining verbiage can be removed as well. Have a good afternoon.

**Comment by balor** [comment]
Thanks for the notice. It's still wip, was planning to refresh readme along with package meta and version, but the info come in handy!

**Comment by jas-** [comment]
Any eta on a new release?

**Comment by balor** [comment]
Will release it till 21 of march, after return from busy trip.

**Comment by jas-** [comment]
Ok, thanks for a good and long lasting module

**Comment by balor** [comment]
Hah, had May in mind ofc, my bad :)

**Comment by balor** [comment]
Readme updated, reflecting the change mentioned here.
